/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AktualnosciRouteImport } from './routes/aktualnosci'
import { Route as BityRouteImport } from './routes/bity'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as KlipyRouteImport } from './routes/klipy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AktualnosciRoute = AktualnosciRouteImport.update({
  id: '/aktualnosci',
  path: '/aktualnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const BityRoute = BityRouteImport.update({
  id: '/bity',
  path: '/bity',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const KlipyRoute = KlipyRouteImport.update({
  id: '/klipy',
  path: '/klipy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aktualnosci': typeof AktualnosciRoute
  '/bity': typeof BityRoute
  '/galeria': typeof GaleriaRoute
  '/klipy': typeof KlipyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aktualnosci': typeof AktualnosciRoute
  '/bity': typeof BityRoute
  '/galeria': typeof GaleriaRoute
  '/klipy': typeof KlipyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aktualnosci': typeof AktualnosciRoute
  '/bity': typeof BityRoute
  '/galeria': typeof GaleriaRoute
  '/klipy': typeof KlipyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/aktualnosci' | '/bity' | '/galeria' | '/klipy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/aktualnosci' | '/bity' | '/galeria' | '/klipy'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aktualnosci'
    | '/bity'
    | '/galeria'
    | '/klipy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AktualnosciRoute: typeof AktualnosciRoute
  BityRoute: typeof BityRoute
  GaleriaRoute: typeof GaleriaRoute
  KlipyRoute: typeof KlipyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktualnosci': {
      id: '/aktualnosci'
      path: '/aktualnosci'
      fullPath: '/aktualnosci'
      preLoaderRoute: typeof AktualnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bity': {
      id: '/bity'
      path: '/bity'
      fullPath: '/bity'
      preLoaderRoute: typeof BityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klipy': {
      id: '/klipy'
      path: '/klipy'
      fullPath: '/klipy'
      preLoaderRoute: typeof KlipyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AktualnosciRoute: AktualnosciRoute,
  BityRoute: BityRoute,
  GaleriaRoute: GaleriaRoute,
  KlipyRoute: KlipyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
